### ISSUE TITLE
Improvements to Guild command

### ISSUE THREAD

**Issue by binaryoverload** [CascadeBot/CascadeBot#102]
Some minor improvements need to be done to the guild command. These should be relatively easy.

---
Add a `;guild info` command that shows information such as:
- The flags that are enabled/disabled. This should be shown as a list of all the tags with a ✅ or a ❌next to it
- The date our bot joined the guild
 
Nothing else for now, this will eventually include more information such as whether the guild is blocked etc. This `;guild info` command should also have an optional guildId argument like so `;guild info [guildId]`

---
Add to the `;flag list` command by telling us what flags the user has enabled at the time. This could be done with ✅ and ❌ or some other way.

**Comment by JamesHawkinss** [comment]
OwO

**Comment by JamesHawkinss** [comment]
Ready for review y'all
