### ISSUE TITLE
Permissions command

### ISSUE THREAD

**Issue by weeryan17** [CascadeBot/CascadeBot#106]
So I just realized we don't have a permissions command yet, and that's kind of important.
We need to account for both permission modes via commands, and probably have a way to test perms.
As permissions are complicated we're open to ideas for command structure.

**Comment by binaryoverload** [comment]
I'm thinking we do something similar to how [GroupManager structures their commands](https://wiki.mc-ess.net/wiki/Group_Manager/Commands). Now there's two ways of doing this: one way is to have separate commands for editing users, groups and other items; the other way is to, like in group manager, have a completely separate command for each action. I personally always found a command for every option quite confusing so I would prefer to do it the former way i.e. have a separate for editing users, groups and executing other actions.

**Comment by weeryan17** [comment]
I'm actually thinking maybe one giant permissions command might not be too bad this time around, and one of the main issues we had with that was in code, and now that we have sub commands the code shouldn't be too bad. I also like the different group ans user commands idea, but we need to find a way to preface those commands so your not just running `;user` as that's very ambiguous.

**Comment by binaryoverload** [comment]
Yeah I hear you, I'm gonna say let's talk about this more in the meeting

**Comment by weeryan17** [comment]
after talking about it during the meeting we decided on doing module based permission command
example
`;userperms <add/remove/etc>`
`;groupperms <add/remove/etc>`
`;misc`
