### ISSUE TITLE
Settings annotation

### ISSUE THREAD

**Issue by binaryoverload** [CascadeBot/CascadeBot#109]
At the moment, our current settings for each of the guilds is quite fragmented. We have most of the boolean settings in `GuildSettings` and other settings we don't want the user to directly change in the `GuildData`. 

This causes issues for a number of reasons:
 - The settings are put in different places so it is not obvious where a setting would be contained
 - There is no way to add meta information that will be needed for the panel such as:
    - The module the setting belongs to
    - Whether a flag is required to access it
 - To stop a user editing a setting, we have to put it in a different place

I propose a different solution where all settings (Boolean or not) will be places in GuildSettings and each of them given a @Setting annotation which will allow us to specify properties such as:
  - The module the setting belongs to
  - Whether a flag is required to access it
  - Whether the user is able to edit it through the settings command

As well as anything else we need. This will also make our lives a lot easier when it comes to allowing users to import and export settings as everything will be contained in one place.

@weeryan17 Thoughts?

**Comment by weeryan17** [comment]
I mean the GuildSettings is what users can change directly makes seance in my mind at least, and makes it easier for us to just use reflection to change everything their. Maybe we could have a class for settings we want a user to directly change, and then a class for settings that are close to the user directly changing it (like enabled modules for example), but yeah the settings annotation sounds nice, so it's easier for jvs to reference things.

**Comment by binaryoverload** [comment]
My idea with the annotation is that we can use the reflection we when already and just make it check whether the user is able to edit it directly. This way they're both in the same place and we can easily serialise the GuildSettings class to import and export data

**Comment by weeryan17** [comment]
Well yes we can do that we'll still run into issues of what goes in guild settings and what goes in guild data, as everything in guild data could be considered a setting.
