### ISSUE TITLE
[Bug] Userinfo does not return right

### ISSUE THREAD

**Issue by DeadlyFirex** [CascadeBot/CascadeBot#126]
**Describe the bug**
Whenever you try to get information on valid user bot cannot see, it does not return invid user embed

**To Reproduce**
1. Type ;userinfo `ID from someone bot cannot see`

**Expected behavior**
- Catched error and clear embed telling that the user is invalid
> Instead, it posts a stacktrace on hastebin

**Screenshots**
_nothing_

**Additional context**
Add any other context about the problem here such as what device for visual bugs.
_nothing_

**Comment by binaryoverload** [comment]
`;userinfo` on its own will not error. This must be with a user the bot can't see. We need more screenshot/stacktraces please

**Comment by Ikinon** [comment]
Can reproduce https://hastebin.com/riyinisoko,
Give a user that cannot be seen by the user by ID

**Comment by JamesHawkinss** [comment]
Can reproduce https://hastebin.com/vecezovege
Provide the ID of a user that the bot cannot see.
Command: `;userinfo 80972065296887808`
