### ISSUE TITLE
Status Command

### ISSUE THREAD

**Issue by JamesHawkinss** [CascadeBot/CascadeBot#129]
I was looking through Flare code and I thought it would be a cool idea to have a Status command, to be able to view the bot's status. I'm sure this will inevitably be shown on the Web panel, but I thought I'd make a suggestion for such a command here.

For reference, here's the Flare command: https://github.com/FlareBot/FlareBot/blob/master/src/main/java/stream/flarebot/flarebot/commands/informational/StatusCommand.java

What do y'all think?

**Comment by DeadlyFirex** [comment]
I think this should be in the Beta, but that's my personal opinion, it looks like the perfect command to take a look at how the backend behaves instead of manually checking, highly recommended, we could extend this however. In my opinion a must have
