### ISSUE TITLE
Purge command

### ISSUE THREAD

**Issue by DeadlyFirex** [CascadeBot/CascadeBot#155]
A clean command that is subdivided into cleaning messages in the following forms:
- [x] Images
- [x] Links
- [x] Specific user
- [x] All messages
- [x] Bot messages
- [x] Messages that contain something
( I am working on this )

**Comment by DeadlyFirex** [comment]
> All messages
> Bot messages
> Messages that contain something
Are all done

**Comment by binaryoverload** [comment]
Done a checklist for you :P

**Comment by DeadlyFirex** [comment]
All commands are done a very long ago, going to work on optimization today and tommorow, then PRA

**Comment by DeadlyFirex** [comment]
Everythings done!
