### ISSUE TITLE
[Bug] LavaPlayer + YouTube API

### ISSUE THREAD

**Issue by JamesHawkinss** [CascadeBot/CascadeBot#169]
**Describe the bug**
When telling the bot to play music, it errors with the following error: https://hasteb.in/axixixon

**To Reproduce**
1. Join the bot to a channel
2. Tell the bot to play music
3. BAM it broke

**Expected behavior**
I expected the bot to play music

**Comment by JamesHawkinss** [comment]
Fix by updating LavaPlayer to latest version.

**Comment by mrjvs** [comment]
1.3.19 to be exact.

**Comment by binaryoverload** [comment]
Do we know that updating lavaplayer fixes this? If so, make a PR. Doesn't matter that it's single line

**Comment by mrjvs** [comment]
> 
> 
> Do we know that updating lavaplayer fixes this? If so, make a PR. Doesn't matter that it's single line

I've already confirmed that it is indeed fixed in 1.3.19

**Comment by JamesHawkinss** [comment]
Issue fixed on production, thanks Ryan.
