### ISSUE TITLE
Uxui Improvements

### ISSUE THREAD

**Issue by JamesHawkinss** [CascadeBot/CascadeBot#189]
# James
- [x] Add aliases to usage command - @JamesHawkinss 
- [x] Add icon to ;stats shard status - @JamesHawkinss 
- [x] Settings list improve - @JamesHawkinss 
- [x] setting set. Turn setting in code block - @JamesHawkinss 
- [x] Reformat flags to ICON - FLAG - @JamesHawkinss 
- [x] Add advertisement to flags command - @JamesHawkinss 
- [x] Tag needs alias "tags" - @JamesHawkinss 
- [x] Tag list needs reformat and not on usage - @JamesHawkinss 
- [x] ;tag shows up on usage - @JamesHawkinss 
- [x] ;tag `<tag>` needs improved description - @JamesHawkinss 
- [x] Inconsistent tag/name in usage - @JamesHawkinss 
- [x] Softban no args should reply usage - @JamesHawkinss 
- [x] Todo should have alias "todolist" - @JamesHawkinss 
- [x] Todo create > add > remove = missing embed. - @JamesHawkinss 
- [x] Inconsistent naming in todo usage - @JamesHawkinss 
- [x] usage missing `help [module]` - @JamesHawkinss 
- [x] ;loop invalid mode broken - @JamesHawkinss 
- [x] ;help `<invalid module>` broken - @JamesHawkinss 
- [ ] ;loop [mode] needs elaboration on modes - @JamesHawkinss 
- [x] Skip usage [force] needs to be sub command - @JamesHawkinss 
- [x] Queue usage [scope] needs to be sub command or extra description - @JamesHawkinss 

# Deadly
- [x] Lang string color rgb - @DeadlyFirex 
- [x] Color rgb accept spaces - @DeadlyFirex 
- [x] Settings no args: show list - @DeadlyFirex 
- [x] Random color language string missing - @DeadlyFirex 
- [x] Random command needs min max - @DeadlyFirex 
- [x] Random [amount] needs better description - @DeadlyFirex 
- [x] Module list not in usage - @DeadlyFirex 
- [x] Module list needs reformat - @DeadlyFirex 
- [x] Settings needs alias "setting" - @DeadlyFirex 
- [ ] Tag category delete everything in category (needs confirmation) - @DeadlyFirex 
- [x] Purge should ignore own message - @DeadlyFirex 
- [ ] Purge contains `<token>` not clear enough - @DeadlyFirex 
- [ ] Todo list command - @DeadlyFirex 
- [ ] Todo delete command - @DeadlyFirex 
- [ ] ;queue root command needs usage - @DeadlyFirex 
- [ ] ;volume usage needs to say percentage - @DeadlyFirex 
- [ ] ;volume root needs new usage - @DeadlyFirex 
- [ ] Groupperms switch doesn't accept mode - @DeadlyFirex 

# Binary
- [x] Forceban breaks with mention - @binaryoverload 
- [x] Forceban needs cancel reaction - @binaryoverload 
- [x] Tags and todo list names should be case insensitive - @binaryoverload 
- [x] Todo requested by missing, cat, dog ( should make decision ) - @binaryoverload 
- [x] If one page, don't have reactions - @binaryoverload 
- [x] search command better title (zero results is broken, keyboard spam) - @binaryoverload 
- [x] Skip vote needs fixing and embed @binaryoverload 
- [x] ;seek randomnum is broken - @binaryoverload 
- [x] Ban reason doesn't work with forceban - @binaryoverload 
- [x] Groupperms delete needs cancel button - @binaryoverload 
- [x] Groupperms list needs embed - @binaryoverload 
- [x] Stats command needs localising - @binaryoverload 
- [x] Requested by... needs localising - @binaryoverload 
- [ ] ;filters operator & type need localising - @binaryoverload 
- [x] Playing command "amount played" needs localising - @binaryoverload 
- [ ] Roles command table layout improvement?
- [ ] Todo list send, title not localised

**Comment by weeryan17** [comment]
> Groupperms delete needs cancel button

that should go on the group picker code if i understand what this is.

**Comment by weeryan17** [comment]
> Add advertisement to flags command

wat

**Comment by DeadlyFirex** [comment]
I will gradually push out changes over the course of the week, expect progress

**Comment by weeryan17** [comment]
@mrjvs @binaryoverload opinions on closing the issue for now, and making a new issue after we do slash commands?

**Comment by mrjvs** [comment]
Agreed

**Comment by binaryoverload** [comment]
Agreed
