### ISSUE TITLE
[Bug] Mentioning cascade doesn't show prefix

### ISSUE THREAD

**Issue by TitusEntertainment** [CascadeBot/CascadeBot#212]
**Describe the bug**
mentioning cascade doesnt show prefix

**To Reproduce**
1. mention cascade

**Expected behavior**
show prefix

**Comment by weeryan17** [comment]
We have this allready

**Comment by mrjvs** [comment]
Broken on prod, should be fixed

**Comment by weeryan17** [comment]
Then an issue should be made saying its broken or this issue re-done. Currently this issue if phrased as a feature requests for a feature we already have.

**Comment by weeryan17** [comment]
Also the issue templates should have been fallowed
