### ISSUE TITLE
Joining a channel when a user plays a song

### ISSUE THREAD

**Issue by binaryoverload** [CascadeBot/CascadeBot#217]
It's been requested for the `;play` command to automatically join the bot to the current channel (If the user is in one)

Requirements: 
 - If the user is not in a voice channel, the track is just played and the bot stays where it is
 - If the user is in a different channel than the user, the user needs `join.other` for the join to happen

@JamesHawkinss

**Comment by JamesHawkinss** [comment]
assign plox
