### ISSUE TITLE
[Feature request] Vote skip takes a long time

### ISSUE THREAD

**Issue by mrjvs** [CascadeBot/CascadeBot#221]
**Is your feature request related to a problem? Please describe.**
Skip vote takes a long time.

**Describe the solution you'd like**
Skip vote time cut by half. so 15 seconds.
30 seconds is a big portion of a song already. better of not skipping it al together if it takes a long time.
On top of that I would also like for it to check for if the more than 50% of people in vc has voted yes.
if thats the case then just skip.

**Describe alternatives you've considered**
Not applicable

**Additional context**
agreed by 2 other people in cascade guild
(dont count bots in the list of people in vc)

**Comment by weeryan17** [comment]
I don't fully agree with lowering the vote time to the degree you suggested. I see the point in we might want to lower it, but we want to give people enough time to make sure everyone votes. This might be a thing we make a vote for our testers to see what they think.

**Comment by JamesHawkinss** [comment]
I agree that the time should be shortened. Perhaps we can make it skip as soon as the threshold is met?

**Comment by weeryan17** [comment]
![Screenshot from 2020-05-17 09-34-28](https://user-images.githubusercontent.com/10491247/82151570-a5ba1580-9821-11ea-976c-50f8e20dfeb7.png)

**Comment by villChurch** [comment]
If this is still up for grabs then happy to have a go.

**Comment by weeryan17** [comment]
Good luck. If you need any help let us know.

**Comment by mrjvs** [comment]
The functionality (10s initial, +5s for every new vote) will probably require editing of the votes package (utils/votes). it only allows a static time without a way to update a time.

**Comment by villChurch** [comment]
With this feature, I take it if 50% of people in vc voted you still want it to skip even with the new timer changes?

**Comment by binaryoverload** [comment]
Yup! :)
