### ISSUE TITLE
Error Message Manager

### ISSUE THREAD

**Issue by JamesHawkinss** [CascadeBot/CascadeBot#52]
The main method (that's what it's called right?) will be called errorMessage and have the following stuff 

* `noUserFound` - A standard error message for when the bot can't find the specified user
* `noGuildFound` - Similar to the above but for guilds
* `missingPermssion` - When the bot doesn't have the required permission

If anyone has any suggestions for more error messages feel free to comment them, or if you have any idea how this might work.

**Comment by binaryoverload** [comment]
@weeryan17 Interested on your feedback on this

**Comment by binaryoverload** [comment]
How I imagine this working is passing in a parameter of either `Object...` or `String...` and using that like String.format(). `Object...` would be better as it allows anything to be passed into it.

**Comment by weeryan17** [comment]
@JamesHawkinss you thinking of having multiple methods, or just one method? in your suggest you both said main method and then listed multiple methods

**Comment by JamesHawkinss** [comment]
> @JamesHawkinss you thinking of having multiple methods, or just one method? in your suggest you both said main method and then listed multiple methods

I think just one main method for now, but if you think multiple methods would be better than we should go with that?

**Comment by weeryan17** [comment]
I was asking you because you said main method and then listed multiple methods. Start doing some planning for now the method will work.

**Comment by JamesHawkinss** [comment]
> I was asking you because you said main method and then listed multiple methods. Start doing some planning for now the method will work.

I actually have no idea how it *will* work...

**Comment by binaryoverload** [comment]
I think we should use multiple methods as a single method could get convoluted.

**Comment by binaryoverload** [comment]
A method I'm thinking of goes something like this:
```java
public static void sendUserNotFoundError(TextChannel channel, User user) {
 // send message
}```

**Comment by weeryan17** [comment]
If we're going to be going the multiple methods route it would probably be best to put this in context

**Comment by binaryoverload** [comment]
We could yeah 🤔

**Comment by binaryoverload** [comment]
The only issue I see with that is that if we want to add more error messages that's *another* thing we've plopped into context

**Comment by weeryan17** [comment]
putting it elsewhere will just be harder to access, and cause it to where you have to use two different things to reply. context, and the error handler.

**Comment by binaryoverload** [comment]
I think if we put it in context it'd have to be one method that either accepts a string message (We can store constants somewhere) or an Enum which contains the string to be used.

**Comment by weeryan17** [comment]
I think we need to redesign context overall. it's a little messy atm.

**Comment by binaryoverload** [comment]
If you wanna do that feel free, I don't see a way that we easily could while still maintaining the functionality we need

**Comment by binaryoverload** [comment]
Superceded by #64
