### ISSUE TITLE
Custom colours

### ISSUE THREAD

**Issue by binaryoverload** [CascadeBot/CascadeBot#53]
Use custom colours for the different message types. At current, the different messages types we have are:
- Info
- Success
- Warning
- Moderation
- Danger
- Neutral (Uses Cascade red)

**Comment by binaryoverload** [comment]
Relating to https://github.com/CascadeBot/CascadeBot/blob/dev/src/main/java/com/cascadebot/cascadebot/messaging/MessageType.java

**Comment by binaryoverload** [comment]
The custom colours should be put in `com.cascadebot.shared.SharedConstants`

**Comment by JamesHawkinss** [comment]
> Relating to https://github.com/CascadeBot/CascadeBot/blob/dev/src/main/java/com/cascadebot/cascadebot/messaging/MessageType.java

now https://github.com/CascadeBot/CascadeBot/blob/dev/src/main/java/org/cascadebot/cascadebot/messaging/MessageType.java

**Comment by binaryoverload** [comment]
@mrjvs I'd like this for Alpha, will you be able to get this done?
