### ISSUE TITLE
Command Context Redesign

### ISSUE THREAD

**Issue by weeryan17** [CascadeBot/CascadeBot#54]
So we where talking about this recently in issue #52. I have a few ideas of how we could handle this.
1. Enumize command context:
    Currently in command context we have a buch of replyInfo, replyWarning, ect.... we could switch those over to being replyTyped and use the enum we already have for message types.
2. Expand the messaging package and move all messaging stuff over their.
    This would allow us to split things out more, but make it slightly harder to access
    `MessagingClass.something()` instead of `context.something()`

I want to avoid having context having messaging stuff, and having separate messaging stuff as it could get confusing where things are, and where to put new things.

If you have any other ideas feel free to put them here.

**Comment by binaryoverload** [comment]
I do like the idea of enumising command context (Enums :heart_eyes:). I think adding an overload for `reply(` would be better instead of creating a new method as `replyTyped` reads weirdly in my head. 

Would look something like this `reply(MessageType.DANGER, "Ahhhhh")`

The only thing with this is it makes it longer to type in the commands but the trade off is probably worth it in terms of organisation.

**Comment by weeryan17** [comment]
I was leaning more twords expand the messaging package as cleaning up context now can still cause it to become huge later where as with expanding the messageing package we'd have things split out better, and we really whouldn't fill up any of the classes, although I'm fine with ether method.

**Comment by binaryoverload** [comment]
Oh I didn't realise that it was two different methods woops mb. Yeah I'm with you on moving to the Messaging class although I do think we should keep some basic reply methods in context for ease of use perhaps?

**Comment by weeryan17** [comment]
Yegh maybe some really basig ones, but anything more complex should be in a separate class

**Comment by weeryan17** [comment]
@binaryoverload we good to go with working on this then?

**Comment by binaryoverload** [comment]
If you're happy to go for it :)

**Comment by weeryan17** [comment]
@binaryoverload can you take a look at the latest commit on the `core/command-context` branch and give my your opinions.

**Comment by weeryan17** [comment]
pr #74
