### ISSUE TITLE
Command/Feature flagging

### ISSUE THREAD

**Issue by binaryoverload** [CascadeBot/CascadeBot#58]
Add functionality to add flags to things so we can check whether this feature should be done. For now, this will just be the `beta` flag to introduce commands/features that are only for the beta program.

The flags I can forsee us needing:
 - Alpha??
 - Beta
 - Patreon Tier 1    
 - Patreon Tier 2   
 - Patreon Tier 3    

**These are just examples for the Patreon!**
I won't be implementing anything other than the first 2 for now as we don't know how we will structure our Patreon stuff.

---

Implementation proposal:
 - `Flags.java` enum to contain the flags
 - Introduce a `getFlags()` method to `ICommandExecutable` that returns an EnumSet representing the flags it requires to execute
 - Add a Set of enabled flags into guild data
    - This will be used to enable things like beta or Patreon access
 - Add a subcommand to `guild` to enable and disable beta
   - `;guild beta [guildId]`
   - Maybe this could be modified to work with all flags in the enum?

**Comment by binaryoverload** [comment]
Requesting review from: @weeryan17 and @mrjvs

**Comment by mrjvs** [comment]
Alpha/indev could be nice. waiting for Patreon meeting for this would be best btw

**Comment by binaryoverload** [comment]
Well all the Patreon would be is extra flags. Right now I just have Alpha/Beta to implement, I'm definitely not adding Patreon stuff till we have a solid plan.

On Flare we used Beta for indev stuff, what would you say the difference between the two is @mrjvs?

**Comment by weeryan17** [comment]
I mean alpha is essentially the testbot. I understand having a beta flag to give people access to some feature early on the main bot, but alpha is really just the test bot witch we shouldn't be releasing publicly so no alpha flag i'd say,

**Comment by binaryoverload** [comment]
What I can do is start implementing the core parts of this feature and leave the specific details to be discussed about, sound okay?

**Comment by weeryan17** [comment]
Sounds fine
