### ISSUE TITLE
Forceban Command

### ISSUE THREAD

**Issue by binaryoverload** [CascadeBot/CascadeBot#62]
At the moment, we do not have a force ban command which means that people can only ban people from their guild. 

Should we: 
 - Add a force ban command which retrieves a user 
 - Add a way for the current ban command to "force ban" a user

**Comment by binaryoverload** [comment]
@weeryan17 Opinion please 😄

**Comment by JamesHawkinss** [comment]
BAGSY

**Comment by JamesHawkinss** [comment]
@binaryoverload we should add a force ban option to the current command. Perhaps if the end of the command contains -forceban then it'll force ban them?

**Comment by weeryan17** [comment]
I like the idea of implementing it into the ban command, but we need to find a good way to do it.

**Comment by weeryan17** [comment]
Maybe if we don't find the member in the guild but find a user we could tell them `we couldn't find [user] in the guild would you like to force ban them?` with a button. I believe we could even use confirm utils for this.

**Comment by binaryoverload** [comment]
Thing is, I don't want to always be making requests to discord if the user doesn't exist in any of the guilds the bot is in cause that will end up being a lot of requests. This is why we originally used the forceban command as we would only make the request if the user wanted us to.

**Comment by weeryan17** [comment]
I mean we could look for them in the guild first and if they're not found their look to discord only if they provided an id

**Comment by binaryoverload** [comment]
Could do yeah

**Comment by binaryoverload** [comment]
@JamesHawkinss You okay to have a look at this?

**Comment by JamesHawkinss** [comment]
I'll see what I can come up with :)

**Comment by JamesHawkinss** [comment]
#67
