### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by binaryoverload** [CascadeBot/CascadeBot#72]
Woohoo it's that time to start getting a good ol' music system implemented :D

This issue will act as a overal TODO list, I'm welcoming different people to PR different sections

### Core management functionality
Each guild requires a music manager that handles:
 - [x] The music queue
 - [x] Currently playing track
 - [x] Playlists
   - [x] Saving 
   - [x] Loading

This music manager will be stored in `GuildData` as a transient field so it doesn't get saved.

Playlists are able to be stored in two "scopes": guild and user
  - When saving, by default playlists will be stored in the guild scope but users can opt to have it in their user scope
  - Since playlists are not always stored specific to a guild, they will be stored in a separate collection. The field `owner_id` will be used to link to either a guild or a user depending on scope.
    - **Note:** On its own `owner_id` is not guaranteed to be either a guild id or user id; only with the `scope` field can this be determined!

### Basic music commands
- [x] Pause - Pauses a played track
- [x] Resume - Resumes a played track
- [x] Stop - Stop current track and remove it from the queue (Not sure about this function)
- [x] Join/Leave - Asks bot to join/leave the voice channel
- [x] Loop - Sets the current queue to loop (Requires proper queue handling) Perhaps have an argument to set different loop modes? i.e. `DISABLED`, `REPEAT` (playlist), `REPEAT_ONCE` (current song) 
- [x] Shuffle - Shuffle's the current queue
- [x] Song - View the current playlist song
- [x] Volume - Change Volume
- [x] Play - Either resumes a paused track or load a item
- [x] Search - Searches YouTube (Or other stuff?) for tracks
- [x] Queue - View the current queue
- [x] Skip - Skips the current song but does voting too

### Playlist commands
- [x] Save
- [x] Load

**Comment by JamesHawkinss** [comment]
WOOOOOOOO MUSIC WOOOOOOO

**Comment by weeryan17** [comment]
@JamesHawkinss and @Ikinon if you two want to get started I already have a lot of the stuff their for you two to make commands.

**Comment by weeryan17** [comment]
Btw the shuffle command should also be a thing

**Comment by JamesHawkinss** [comment]
How much more needs to be done on this one?

**Comment by binaryoverload** [comment]
Queue, load and save

**Comment by weeryan17** [comment]
Closing this as music is done
