### ISSUE TITLE
Tags command

### ISSUE THREAD

**Issue by binaryoverload** [CascadeBot/CascadeBot#93]
And so we introduce the lovely tags system or "text-based custom commands" as @weeryan17 likes to call it.

This is effectively a system that maps a key to text. A common use for this is rules, knowledge base and support messages for servers along with much more!

Alongside this, we will be adding a category system that will allow tags to be split into different categories such as moderation, knowledge base etc. These categories will not be used anywhere else and will be checked and created dynamically with tags.
```java
class Tag {
    String content
    String category
}
```

There will be a `Map<String, Tag>` added to `GuildData` that will store all the tags for a guild. The appropriate methods should be added to add/remove tags and get the map of tags (immutable!)

A setting should be added to `GuildSettings` called `allowTagCommands` which enables or disables doing `;<tagname>`; this should be enabled by default. The tags commands will be processed after the built in commands in order to avoid conflicts.

A tag command should be created with different usages:
 - `;tag create <tagname> <content>`
 - `;tag create <tagname[:category]> <content>`
 - `;tag delete <tagname>`
 - `;tag <tagname`
 - `;tag list`

**Comment by weeryan17** [comment]
@binaryoverload you should also mention we're going to have variables like `{time}` `{arg[0]}` that he'll need to process.

**Comment by binaryoverload** [comment]
Ah yes, we'll have different variables like member, args, time etc

When the system is more complete we can come to that

**Comment by JamesHawkinss** [comment]
Would someone be happy to help me out with this, not sure exactly where I'd start :,)

**Comment by binaryoverload** [comment]
I'd be happy to, to start with you just need to create the Tag object in `com.cascadebot.cascadebot.data.objects` and add the map to `GuildData` :)

**Comment by binaryoverload** [comment]
The PR #95 is underway.
